### ISSUE TITLE
merge with backupninja?

### ISSUE THREAD

**Issue by anarcat** [mxroo/borg_backupninja#1]
there's an effort to add a borg handler in backupninja here already:

https://0xacab.org/riseuplabs/backupninja/merge_requests/1

is this the same effort? shouldn't those efforts be merged, even if only to avoid conflicts in the naming?

**Comment by mxroo** [comment]
I believe that my changes that were deemed necessary were integrated in to that effort by Benzhaomin, whose efforts I fully support.
